# Generated by Django 3.2.7 on 2021-09-16 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='favorites',
            name='name',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
