# Generated by Django 3.2.7 on 2021-09-16 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0003_remove_favorites_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='favorites',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
    ]
