# Generated by Django 3.2.7 on 2021-09-16 21:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0004_alter_favorites_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='favorites',
            name='id',
        ),
        migrations.AlterField(
            model_name='favorites',
            name='image_url',
            field=models.URLField(primary_key=True, serialize=False),
        ),
    ]
